export const API_ROUTES = {
  auth: {
    login: '/auth/login',
    refresh: '/auth/refresh',
    logout: '/auth/logout',
    me: '/auth/me',
  },
  buildings: {
    list: '/buildings',
    detail: (id: string) => `/buildings/${id}`,
  },
  rooms: {
    list: '/rooms',
    detail: (id: string) => `/rooms/${id}`,
    occupancy: (id: string) => `/rooms/${id}/occupancy`,
  },
  tenants: {
    list: '/tenants',
    detail: (id: string) => `/tenants/${id}`,
  },
  contracts: {
    list: '/contracts',
    detail: (id: string) => `/contracts/${id}`,
  },
  invoices: {
    list: '/invoices',
    detail: (id: string) => `/invoices/${id}`,
    prefill: '/invoices/prefill',
    fromReading: (utilityReadingId: string) => `/invoices/from-reading/${utilityReadingId}`,
    generateRoom: '/invoices/generate/room',
    generateBuilding: '/invoices/generate/building',
    generateAll: '/invoices/generate/all',
    issue: (id: string) => `/invoices/${id}/issue`,
    void: (id: string) => `/invoices/${id}/void`,
    markOverdue: (id: string) => `/invoices/${id}/mark-overdue`,
    adjustments: (id: string) => `/invoices/${id}/adjustments`,
  },
  payments: {
    requests: '/payments/requests',
    requestDetail: (id: string) => `/payments/requests/${id}`,
    invoiceRequest: (invoiceId: string) => `/payments/invoices/${invoiceId}/request`,
    cancelRequest: (id: string) => `/payments/requests/${id}/cancel`,
    expireRequest: (id: string) => `/payments/requests/${id}/expire`,
    submitProof: (id: string) => `/payments/requests/${id}/proofs`,
    approveProof: (id: string) => `/payments/proofs/${id}/approve`,
    rejectProof: (id: string) => `/payments/proofs/${id}/reject`,
  },
  fixedCharges: {
    catalog: '/fixed-charges/catalog',
    catalogDetail: (id: string) => `/fixed-charges/catalog/${id}`,
    buildingCharges: '/fixed-charges/building-charges',
    buildingChargeDetail: (id: string) => `/fixed-charges/building-charges/${id}`,
    roomOverrides: '/fixed-charges/room-overrides',
    roomOverrideDetail: (id: string) => `/fixed-charges/room-overrides/${id}`,
    contractOverrides: '/fixed-charges/contract-overrides',
    contractOverrideDetail: (id: string) => `/fixed-charges/contract-overrides/${id}`,
    roomMonthExtras: '/fixed-charges/room-month-extras',
    roomMonthExtraDetail: (id: string) => `/fixed-charges/room-month-extras/${id}`,
    resolve: '/fixed-charges/resolve',
  },
  utilityReadings: {
    list: '/utility-readings',
    detail: (id: string) => `/utility-readings/${id}`,
    create: '/utility-readings',
    evidence: (id: string) => `/utility-readings/${id}/evidence`,
    approve: (id: string) => `/utility-readings/${id}/approve`,
    reject: (id: string) => `/utility-readings/${id}/reject`,
  },
  utilityRates: {
    list: '/utility-rates',
    detail: (id: string) => `/utility-rates/${id}`,
  },
  me: {
    room: '/me/room',
    roommates: '/me/roommates',
    currentBill: '/me/current-bill',
    invoiceDetail: (id: string) => `/me/invoices/${id}`,
    utilityReadings: '/me/utility-readings',
    paymentStatus: '/me/payment-status',
  },
  uploads: {
    metadata: '/uploads/metadata',
  },
} as const
